[tools]
nodejs = "23.1.0"
"gem:kamal" = "2.11.0"

# fcov == "fast coverage" by skipping migrations checking. Save that for CI.
# -n 8 --dist loadfile, 8 CPUs, 515 tests, 20s
# -n 4 --dist loadfile, 4 CPUs, 515 tests, 13s
# -n 2 --dist loadfile, 4 CPUs, 515 tests, 15s
# With coverage sysmon enabled, -n 6 --dist worksteal ran 499 tests in about 10s.
[tasks.test]
description = "Run tests"
run = "uv run pytest --cov=homeschool -n 6 --dist worksteal -q"
