# Generated by Django 3.1.2 on 2020-11-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="flag",
            name="everyone",
            field=models.BooleanField(
                blank=True,
                help_text=(
                    "Flip this flag on (Yes) or off (No) for everyone, overriding all"
                    " other settings. Leave as Unknown to use normally."
                ),
                null=True,
                verbose_name="Everyone",
            ),
        )
    ]
