# Generated by Django 3.0.7 on 2020-08-16 17:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("title", models.CharField(max_length=512)),
                ("details", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="courses.Course",
                    ),
                ),
            ],
        )
    ]
