# Generated by Django 3.1.2 on 2020-11-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("courses", "0002_courseresource")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is this course active in the schedule?"
            ),
        )
    ]
