# Generated by Django 3.1.8 on 2021-04-22 03:56

import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("courses", "0003_course_is_active")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",  # noqa
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="courseresource",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",  # noqa
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="coursetask",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",  # noqa
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
