# Generated by Django 3.1.8 on 2021-04-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("courses", "0004_auto_20210422_0356")]

    operations = [
        migrations.RemoveField(model_name="course", name="uuid"),
        migrations.RemoveField(model_name="courseresource", name="uuid"),
        migrations.RemoveField(model_name="coursetask", name="uuid"),
    ]
