# Generated by Django 4.1.7 on 2023-03-23 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_remove_uuids"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetask",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                help_text="An associated course resource",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="courses.courseresource",
            ),
        ),
    ]
