# Generated by Django 3.2 on 2021-05-20 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("schools", "0003_remove_uuids"), ("students", "0004_remove_uuids")]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="grade_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="schools.gradelevel",
            ),
        )
    ]
