# Generated by Django 3.2.12 on 2022-02-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_alter_enrollment_grade_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursework",
            name="completed_date",
            field=models.DateField(blank=True, db_index=True),
        ),
    ]
