# Generated by Django 3.2.3 on 2021-06-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("referrals", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        )
    ]
