# Generated by Django 5.1 on 2024-10-15 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0002_referral_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Referral",
        ),
    ]
