# Generated by Django 3.1.4 on 2021-01-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Exempt"),
                    (2, "Beta"),
                    (3, "Trialing"),
                    (4, "Active"),
                    (5, "Past Due"),
                    (6, "Canceled"),
                ],
                db_index=True,
                default=3,
            ),
        )
    ]
