# Generated by Django 4.0.5 on 2022-07-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_historicalaccount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalaccount",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical account",
                "verbose_name_plural": "historical accounts",
            },
        ),
        migrations.AlterField(
            model_name="historicalaccount",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
