# Generated by Django 4.0.3 on 2022-04-08 05:04

import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models

import homeschool.reports.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0005_grade_level_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",  # noqa
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.FileField(upload_to=homeschool.reports.models.report_path),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Pending"), (2, "Complete")], default=1
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.schoolyear",
                    ),
                ),
            ],
        ),
    ]
