# Generated by Django 3.1.8 on 2021-04-22 14:33

import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("schools", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="gradelevel",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",  # noqa
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="schoolbreak",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",  # noqa
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",  # noqa
                min_length=7,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
