# Generated by Django 3.1.8 on 2021-04-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("schools", "0002_auto_20210422_1433")]

    operations = [
        migrations.RemoveField(model_name="gradelevel", name="uuid"),
        migrations.RemoveField(model_name="schoolbreak", name="uuid"),
        migrations.RemoveField(model_name="schoolyear", name="uuid"),
    ]
