# Generated by Django 3.2.5 on 2021-08-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_enrollment_grade_level"),
        ("schools", "0003_remove_uuids"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolbreak",
            name="students",
            field=models.ManyToManyField(to="students.Student"),
        )
    ]
